# This is a basic workflow to help you get started with Actions

name: Production_deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
   build_frontend_job:
    if: github.event_name == 'push'
    name: Build frontend code
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Node.js
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 14
          check-latest: true
      - run: npm install
      - run: npm run build
        
   deploy_job:
      needs: build_frontend_job
    # The type of runner that the job will run on
      runs-on: ubuntu-latest
      name: Build and Deploy Site
      
    # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: true
          
      # Deploy site to domain 
      - name: ftp-action

        uses: sebastianpopp/ftp-action@v2.0.0
        with:
          # FTP host
          host: linux91.unoeuro.com
          # FTP user
          user: mikkelraev.dk
          # FTP password
          password: mikkelhn1
          # Force SSL encryption
          forceSsl: false
          # Local directory
          localDir: dist
          # Remote directory
          remoteDir: storyblok.portfolio.v2
          
          name: Deploy via git-ftp


   deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: git-ftp push
          uses: sebastianpopp/git-ftp-action@releases/v3
          with:
            url: "ftp://linux91.unoeuro.com"
            user: mikkelraev.dk
            password: mikkelhn1
